#
# Template parameters available:
#   NAMESPACE=${NAMESPACE}
#   COMMENT=${COMMENT}
#   OPERATOR_VERSION=${OPERATOR_VERSION}
#   CH_USERNAME_SECRET_PLAIN=${CH_USERNAME_SECRET_PLAIN}
#   CH_PASSWORD_SECRET_PLAIN=${CH_PASSWORD_SECRET_PLAIN}
#
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-operator
  ${COMMENT}namespace: ${NAMESPACE}
  labels:
    clickhouse.altinity.com/chop: ${OPERATOR_VERSION}
    app: clickhouse-operator
type: Opaque
stringData:
  username: ${CH_USERNAME_SECRET_PLAIN}
  password: ${CH_PASSWORD_SECRET_PLAIN}
