apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure-cluster-secret-02"
spec:
  configuration:
    clusters:
      - name: "plaintext"
        secure: "True"
        secret:
          value: "plaintext secret"
        layout:
          shardsCount: 2
          replicasCount: 2
