apiVersion: "v1"
kind: "Secret"
metadata:
  name: "secure-cluster-secret-03-secret"
type: "Opaque"
stringData:
  secret: "secret kept in the secret"
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure-cluster-secret-03"
spec:
  configuration:
    clusters:
      - name: "secret-ref"
        secure: "True"
        secret:
          valueFrom:
            secretKeyRef:
              name: "secure-cluster-secret-03-secret"
              key: "secret"
        layout:
          shardsCount: 2
          replicasCount: 2
