---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: s3-arn-role
spec:
  defaults:
    templates:
      podTemplate: pod-template-with-aws-profile
  templates:
    podTemplates:
      - name: pod-template-with-aws-profile
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              env:
                - name: AWS_PROFILE
                  value: default
                - name: AWS_CONFIG_FILE
                  value: /etc/clickhouse-server/config.d/aws_profile
  configuration:
    files:
      aws_profile: |-
        [default]
        role_arn=arn:aws:iam::<account-id>:role/<role_name>
        credential_source = Ec2InstanceMetadata
    clusters:
      - name: default
        layout:
          shardsCount: 1
          replicasCount: 1
