#
# This secret is used in combination with config-dev.yaml operator config file
#
apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: chop-clickhouse-credentials
type: Opaque
stringData:
  username: chuser
  password: chpassword
